apiVersion: v1
kind: Service
metadata:
  name: demo-k8s-api-svc
  labels:
    app: demo-k8s-api
spec:
  type: NodePort
  selector:
    app: demo-k8s-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007